### ISSUE TITLE
Error trying to compile

### ISSUE THREAD

**Issue by AbeEstrada** [itsjunetime/tdf#85]
commit ebd902e864201bd6ca299477d8554634c9c52e6c
rustc 1.88.0 (6b00bc388 2025-06-23) (Homebrew)
cargo 1.88.0 (Homebrew)
macOS 15.6 (24G84)

```
cargo build --release
   Compiling kittage v0.1.0 (https://github.com/itsjunetime/kittage.git#d872c44f)
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> ~/.cargo/git/checkouts/vb64-68a93c158492524b/01e7911/src/lib.rs:36:1
   |
36 | #![feature(portable_simd)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `vb64` (lib) due to 1 previous error
```

**Comment by AbeEstrada** [comment]
commit https://github.com/itsjunetime/tdf/commit/69fd8ec7e87a6e08e9ac86d34d7f3188a9d689be

```sh
cargo build --release
warning: file `~/Code/tdf/benches/for_profiling.rs` found to be present in multiple build targets:
  * `bin` target `for_profiling`
  * `bench` target `for_profiling`
   Compiling vb64 v0.1.2 (https://github.com/lukaslihotzki/vb64?branch=update#01e79118)
   Compiling mupdf v0.5.0
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> ~/.cargo/git/checkouts/vb64-68a93c158492524b/01e7911/src/lib.rs:36:1
   |
36 | #![feature(portable_simd)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `vb64` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

**Comment by itsjunetime** [comment]
Theoretically, cargo should automatically detect that you need to use the nightly toolchain to build this (by reading `rust-toolchain.toml`), but I guess it doesn't work sometimes. Either way, you can fix this by running `cargo +nightly build --release` instead. I just updated the README to recommend people specify `+nightly` so nobody else runs into this.

**Comment by AbeEstrada** [comment]
For reference I think the error is in macOS `rust` installed via Homebrew.

I tried:

```sh
brew install rustup
rustup toolchain install nightly
rustup run nightly cargo build --release
```

And I still get an error
